### ISSUE TITLE
Importing huge playlist

### ISSUE THREAD

**Issue by jacobwmorgan** [labay11/spotify2tidal#1]
`Getting tracks from Spotify.
Traceback (most recent call last):
  File "/home/jacob/Desktop/spotify2tidal/importer.py", line 93, in <module>
    run_conversion(sp, sys.argv[1], tidal)
  File "/home/jacob/Desktop/spotify2tidal/importer.py", line 70, in run_conversion
    tracks = load_tracks_from_playlist(sp, spotify_user, playlist['id'])
  File "/home/jacob/Desktop/spotify2tidal/spotify_scanner.py", line 50, in load_tracks_from_playlist
    songs.extend([
  File "/home/jacob/Desktop/spotify2tidal/spotify_scanner.py", line 58, in <listcomp>
    if 'isrc' in s['track']["external_ids"]
TypeError: 'NoneType' object is not subscriptable
`

The link to the playlist is https://open.spotify.com/playlist/49hT6xCBA6PLOzgcaM8ZMD

**Comment by labay11** [comment]
For some reason, two songs in this playlist are not retrieved correctly from the API. Maybe because the tracks are not available anymore. This is the only information that I get:
```
{'added_at': '2020-12-22T00:44:35Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/1177473688'}, 'href': 'https://api.spotify.com/v1/users/1177473688', 'id': '1177473688', 'type': 'user', 'uri': 'spotify:user:1177473688'}, 'is_local': False, 'primary_color': None, 'track': None, 'video_thumbnail': None}
```

```
{'added_at': '2021-06-10T14:06:46Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/1177473688'}, 'href': 'https://api.spotify.com/v1/users/1177473688', 'id': '1177473688', 'type': 'user', 'uri': 'spotify:user:1177473688'}, 'is_local': False, 'primary_color': None, 'track': None, 'video_thumbnail': None}
```

I have pushed a commit so that the code does not stop in those cases. You can try to find the songs according to the date added and compare them with the new Tidal playlist to see which ones are missing.

PD: nice playlist btw! :smiley:

**Comment by jacobwmorgan** [comment]
Thanks its seems to be working now. 
I think they are songs removed by spotify. One seems to be a russian song thats no longer on spotify and the other im not sure of.

Thank you very much for this program btw. I've had this playlist since i was around 14 and 6 years later im glad i can preserve it without having to pay money.

**Comment by labay11** [comment]
> I've had this playlist since i was around 14 and 6 years later im glad i can preserve it without having to pay money.

I can relate, that was my motivation to do this little program. I really think TIDAL should offer this service for free if they want people to change from Spotify.
